FROM node

# Create app directory
RUN npm install -g yarn

# Install app dependencies
RUN yarn global add typescript nodemon

RUN mkdir -p /usr/app/src

COPY ./src /usr/src/app/src
COPY ./package.json /usr/src/app/package.json
COPY ./tsconfig.json /usr/src/app/tsconfig.json

# Bundle app source
WORKDIR /usr/src/app
RUN yarn install

EXPOSE 3000

CMD [ "yarnpkg", "dev" ]