version: '2'

volumes:
  mongodata:
    external: true

services:

  mongo:
    image: mongo:3.2
    command: "mongod --logpath /dev/null --smallfiles --setParameter failIndexKeyTooLong=false"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    network_mode: "bridge"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile-dev
    volumes:
      - ./api-gateway:/usr/src/app
    ports:
      - "3000:3000"
    network_mode: "bridge"

  activity-microservice:
    build:
      context: ./activity-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./activity-microservice:/usr/src/app
    ports:
      - "3001:3001"
    network_mode: "bridge"

  auth-microservice:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./auth-microservice:/usr/src/app
    ports:
      - "3002:3002"
    network_mode: "bridge"

  location-microservice:
    build:
      context: ./location-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./location-microservice:/usr/src/app
    ports:
      - "3003:3003"
    network_mode: "bridge"


  photo-microservice:
    build:
      context: ./photo-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./photo-microservice:/usr/src/app
    ports:
      - "3004:3004"
    network_mode: "bridge"


  timeline-microservice:
    build:
      context: ./timeline-microservice
      dockerfile: Dockerfile-dev
    volumes:
      - ./timeline-microservice:/usr/src/app
    ports:
      - "3005:3005"
    network_mode: "bridge"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
#   volumes:
#     - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
