version: '2'

volumes:
  mongodata:
    external: true

services:

  mongo:
    image: mongo:3.2
    command: "mongod --logpath /dev/null --smallfiles --setParameter failIndexKeyTooLong=false"
    ports:
     - "27017:27017"
    volumes:
     - mongodata:/data/db

  activity-microservice:
    build: ./activity-microservice

  auth-microservice:
    build: ./auth-microservice
    links:
     - mongo

  location-microservice:
    build: ./location-microservice

  storage-microservice:
    build: ./storage-microservice

  timeline-microservice:
    build: ./timeline-microservice

  api-gateway:
    build: ./api-gateway
    ports:
     - "3000:3000"
    links:
     - activity-microservice
     - auth-microservice
     - location-microservice
     - storage-microservice
     - timeline-microservice

  frontend:
    build: ./frontend
    links:
     - api-gateway
    ports:
     - "5000:5000"