FROM node

RUN apt-get update
RUN apt-get install -y net-tools

# Create app directory
RUN npm install -g yarn

# Install app dependencies
RUN yarn global add typescript nodemon

RUN mkdir -p /usr/app/src

COPY ./src /usr/src/app/src
COPY ./package.json /usr/src/app/package.json
COPY ./tsconfig.json /usr/src/app/tsconfig.json

# Bundle app source
WORKDIR /usr/src/app
RUN yarn install
RUN npm rebuild

EXPOSE 3002

CMD [ "yarnpkg", "dev" ]